# Run locally: `npx decap-server`
# local_backend: true

backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts_uk"
    label: "Posts (UK)"
    label_singular: "Post (UK)"
    folder: "content/uk/posts"
    create: true
    slug: "{{slug}}"
    path: "{{year}}-{{month}}-{{day}}-{{slug}}/index"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "posts_de"
    label: "Posts (DE)"
    label_singular: "Post (DE)"
    folder: "content/de/posts"
    create: true
    slug: "{{slug}}"
    path: "{{year}}-{{month}}-{{day}}-{{slug}}/index"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "schedule_uk"
    label: "Schedule (UK)"
    folder: "content/uk/schedule"
    create: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "schedule_de"
    label: "Schedule (DE)"
    folder: "content/de/schedule"
    create: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "sponsors_uk"
    label: "Sponsors (UK)"
    folder: "content/uk/sponsors"
    create: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "sponsors_de"
    label: "Sponsors (DE)"
    folder: "content/de/sponsors"
    create: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "contacts_uk"
    label: "Contacts (UK)"
    folder: "content/uk/contacts"
    create: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "contacts_de"
    label: "Contacts (DE)"
    folder: "content/de/contacts"
    create: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
